### PR TITLE
Add clarity to the parts of a TreePatternMatch

### PR DESCRIPTION
**Pull request by jessitron**
Rod: this needs some of your naming magic. I called things "Thing"
in order that we can come back and name them. They're components
of a tree pattern match.

Main goal: clarify exactly what sort of things make up a TreePatternMatch.
There are scalars, nested trees, and computed properties.
These Things group the value and the pattern match for a property with its name.
Previously these were scattered across the values themselves (nested trees),
$valueMatches (scalars) and nowhere (arrays).

I added an ArrayPatternMatch for Rep to return, so that it can exhibit the $value as previously, and still contain the inner pattern matches even for scalars. This opens the possibility of allowing updates on things in arrays (although that's going to be hard and we need to talk it through).

$thingsInside is a public field only for the Updater stuff to use it.

The components described by the three kinds of Things can be updated inside computations, which I don't like, but it's supported. They retain their original value in a field just on principle. Nested structures don't support updates; we could add that, but it would not have worked before, I don't think, so I made it throw an error.

There is one **BREAKING CHANGE** which is: computations can't add arbitrary stuff to the context. They can only return values which get added to the context as the property defined by the function.
I strongly believe that this is a positive change. It's simpler: properties are all defined in definitions, not in sneaky functions ("Where did this come from??"). Everything that was done is still possible, with a bit of rearranging (see ContextTest and RealWorldTest2). If you do try to add a property to the context, you get an error; it doesn't throw it away silently.

Other things:
   - added $kind to TreePatternMatch for nicer typeguards
   - fixed accidental assignment in NestingTest, which came back as an error in the
 new structure how convenient
   - this fixes the update bug that Rod originally reported, that got me looking at it. I even made it handle computed fields specially so they provide a nice error message like "Error: gav was computed in a function in the microgrammar; you can't update it" (see "update and validate properties" in MicrogrammarUpdateTest)

### CODE REVIEW

**Comment by cdupuis** [comment]
@jessitron please fix those linting errors.

**Comment by johnsonr** [comment]
Code looks good, barring the naming, but this breaks a test in `automation-client-samples`. This relates to updating a nested structure.

To replicate:

- Checkout `automation-client-samples` `master`

```
cd node_modules
cd \@atomist/
rm -rf microgrammar
ln -s /Users/rodjohnson/sforzando-dev/idea-projects/microgrammar/build/src microgrammar
npm run test
```

Output is
```
1) SpringBootVersionUpgrade comment for old Spring project:
     TypeError: Cannot set property value of #<TreePatternMatch> which has only a getter
      at parseUtils_1.doWithAtMostOneMatch.m (src/commands/editor/SpringBootVersionUpgrade.ts:35:37)
      at guardedAction (node_modules/@atomist/automation-client/project/util/parseUtils.js:126:9)
      at file.getContent.then.content (node_modules/@atomist/automation-client/project/util/parseUtils.js:66:17)
```

**Comment by jessitron** [comment]
OK y'all please pause right here this is my demo

it's time to try automating tslint and test runs.

**Comment by johnsonr** [comment]
What's the status of this now?

**Comment by jessitron** [comment]
this is too old now to be useful.

**Pull request closed without merging**
